### ISSUE TITLE
MongoDB fails

### ISSUE THREAD

**Issue by crearis** [dreamfactorysoftware/openshift-dreamfactory-cartridge#4]
Thanks for fixing the install-process of the cartridge in awesome speed!!

But maybe you look at it once again?

After installation:
a) no mongodb is provided
b) access to mongo-dbs hosted in other apps on same domain fails
c) setting up mongodb within the dreamfactory-app doesn't solve the problem, I tried both the official Mongo-2.4 cartridge and the inofficial cartridge from the community (currently 3.2)

Trying to access gives this error, if I click on "create service":
![error](https://cloud.githubusercontent.com/assets/16894154/12655470/61c2a490-c5f9-11e5-890b-8c6eaef9a368.png)

API Error
Required extension or module 'mongo' is not installed or loaded

I would really appreciate if you help out with that or fix it ...
thanks in advance, Hans Dönitz

**Comment by hkhako** [comment]
If my interpretation of your problem is correct, you need php driver for mongodb.  You need to install or compile mongo.so the legacy driver (not the newer mongodb.so).

You can read my cartridge script as an example how to compile mongo.so:
https://github.com/hkhako/OS_Dreamfactory2.0/blob/master/misc/make.sh

**Comment by drewpearce** [comment]
I haven't specifically done it with openshift, but installing mongo.so is easy with pecl.

**Comment by crearis** [comment]
thanks a lot, this will help me out, just made a little research on it 
have a good weekend

**Comment by crearis** [comment]
@hkhako thanks for your advice
I tried everything out as described from you ... but didn't succeed.
One thing I stumbled accross:
The path-variables that dreamfactory applies to me seem as if they have a typo:
they show like:
- /var/lib/openshift/[my home-string]/dreamfactory**//**usr/... something
- the ENV OPENSHIFT_PRIMARY_CARTRIDGE_DIR shows as: /var/lib/openshift/56ab9e1a89f5cfb96d00004d**/**
- shouldn't this be changed?: /var/lib/openshift/56ab9e1a89f5cfb96d00004d
- I can't change through console, Permission denied
- the same is with the workaround @drewpearce proposed: pecl cannot acces mongo.so, cannot be updated ...

Is there a way to fix this even if dreamfactory decides to leave this **unfixed**?

**Comment by hkhako** [comment]
I am not an expert with Openshift.  Why do you need to worry about ENV
OPENSHIFT_PRIMARY_CARTRIDGE_DIR path?
Openshift should be alright.  Double slash is fine, its not a typo and
I think you should have write access to folders in ~/app-root/runtime
if make install didn't work for you because you can't access the extension
folder for php.  You can use a custom php.ini and specify the path of your mongo.so in php.ini

Try the following script and see is it good.  Remember to restart your app
when you got new php extensions.

export OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_HOMEDIR}/app-root/runtime
cd $OPENSHIFT_RUNTIME_DIR
mkdir srv
mkdir srv/mongodb
mkdir srv/libsasl2

# Build SASL

pushd ${OPENSHIFT_RUNTIME_DIR}/tmp
wget ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz
tar -zxf cyrus-sasl-2.1.26.tar.gz
cd cyrus-sasl-2.1.26
./configure \
--prefix=$OPENSHIFT_RUNTIME_DIR/srv/libsasl2
make && make install
export MONGODB_SASL=${OPENSHIFT_RUNTIME_DIR}/srv/libsasl2
export SASL_PATH=${OPENSHIFT_RUNTIME_DIR}/srv/libsasl2
cd ..
rm -f -r *.tar.gz
rm -f -r cyrus-sasl-2.1.26

# Build Mongo Driver

pushd ${OPENSHIFT_RUNTIME_DIR}/tmp
git clone https://github.com/mongodb/mongo-php-driver-legacy.git mongo
cd mongo
phpize
./configure \
--prefix=$OPENSHIFT_RUNTIME_DIR/srv/mongodb \
--enable-developer-flags \
--with-mongodb-sasl=$SASL_PATH
make -j8 all
make install
cp -f -v ./modules/_._ ../../srv/mongodb
cd ..
rm -f -r mongo

**Comment by crearis** [comment]
I tested this through ... didn't get that to work!!
